name: Build
on:
  workflow_call:
    inputs:
      upload-pages-artifact:
        type: boolean
        required: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm start
      - uses: actions/upload-artifact@v3
      - if: ${{ inputs.upload-pages-artifact }}
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist/