name: Test on push deploy github pages
on:
  push:
    branches:
      - main
jobs:
  deploy-to-pages:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ joshnegreanu.com }}
    steps:
      - uses: actions/configure-pages@v3
      - uses: actions/deploy-pages@v2
        id: deployment